name:                runspawner
version:             0.1.0.0
github:              "tux314159/runspawner"
license:             BSD3
author:              "Isaac Yeo"
maintainer:          "tux314159@gmail.com"
copyright:           "2022-2023 Isaac Yeo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tux314159/runspawner#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- clock
- dlist
- text
- mtl
- process
- directory
- filepath
- temporary
- unix
- aeson
- servant
- servant-server
- http-media
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -flate-specialise
- -fspecialise-aggressively

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

library:
  source-dirs: src

executables:
  runspawner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - runspawner
  toy-exe:
    main:                Main.hs
    source-dirs:         app/Toy
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Toy.Main
    dependencies:
    - runspawner

tests:
  runspawner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - runspawner
